/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	appstackv1 "github.com/kenazk/genesis-operator/pkg/apis/appstack/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAppStacks implements AppStackInterface
type FakeAppStacks struct {
	Fake *FakePuppetV1
	ns   string
}

var appstacksResource = schema.GroupVersionResource{Group: "puppet.com", Version: "v1", Resource: "appstacks"}

var appstacksKind = schema.GroupVersionKind{Group: "puppet.com", Version: "v1", Kind: "AppStack"}

// Get takes name of the appStack, and returns the corresponding appStack object, and an error if there is any.
func (c *FakeAppStacks) Get(name string, options v1.GetOptions) (result *appstackv1.AppStack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(appstacksResource, c.ns, name), &appstackv1.AppStack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appstackv1.AppStack), err
}

// List takes label and field selectors, and returns the list of AppStacks that match those selectors.
func (c *FakeAppStacks) List(opts v1.ListOptions) (result *appstackv1.AppStackList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(appstacksResource, appstacksKind, c.ns, opts), &appstackv1.AppStackList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &appstackv1.AppStackList{ListMeta: obj.(*appstackv1.AppStackList).ListMeta}
	for _, item := range obj.(*appstackv1.AppStackList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested appStacks.
func (c *FakeAppStacks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(appstacksResource, c.ns, opts))

}

// Create takes the representation of a appStack and creates it.  Returns the server's representation of the appStack, and an error, if there is any.
func (c *FakeAppStacks) Create(appStack *appstackv1.AppStack) (result *appstackv1.AppStack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(appstacksResource, c.ns, appStack), &appstackv1.AppStack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appstackv1.AppStack), err
}

// Update takes the representation of a appStack and updates it. Returns the server's representation of the appStack, and an error, if there is any.
func (c *FakeAppStacks) Update(appStack *appstackv1.AppStack) (result *appstackv1.AppStack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(appstacksResource, c.ns, appStack), &appstackv1.AppStack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appstackv1.AppStack), err
}

// Delete takes name of the appStack and deletes it. Returns an error if one occurs.
func (c *FakeAppStacks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(appstacksResource, c.ns, name), &appstackv1.AppStack{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAppStacks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(appstacksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &appstackv1.AppStackList{})
	return err
}

// Patch applies the patch and returns the patched appStack.
func (c *FakeAppStacks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *appstackv1.AppStack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(appstacksResource, c.ns, name, pt, data, subresources...), &appstackv1.AppStack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appstackv1.AppStack), err
}
