/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	appstackv1 "github.com/kenazk/genesis-operator/pkg/apis/appstack/v1"
	versioned "github.com/kenazk/genesis-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kenazk/genesis-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/kenazk/genesis-operator/pkg/client/listers/appstack/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AppStackInformer provides access to a shared informer and lister for
// AppStacks.
type AppStackInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.AppStackLister
}

type appStackInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAppStackInformer constructs a new informer for AppStack type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAppStackInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAppStackInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAppStackInformer constructs a new informer for AppStack type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAppStackInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PuppetV1().AppStacks(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PuppetV1().AppStacks(namespace).Watch(options)
			},
		},
		&appstackv1.AppStack{},
		resyncPeriod,
		indexers,
	)
}

func (f *appStackInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAppStackInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *appStackInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&appstackv1.AppStack{}, f.defaultInformer)
}

func (f *appStackInformer) Lister() v1.AppStackLister {
	return v1.NewAppStackLister(f.Informer().GetIndexer())
}
